import select
from utilities.init import parse_arguments, initialize_socket, generate_keys
from utilities.utility import accept_new_connection_handler


class Server:
    """A class representing the server

    Attributes:
        ip - The ip address
        port - The port number
        name - The name of the server
        own_socket - The socket object for the server
        pvt_key - The private key generated by ECDH (via. brainpoolP256r1)
        pub_key - The public key generated by ECDH (via. brainpoolP256r1)
        sockets - A list containing sockets to monitor (using select() function)
        client_dict - A dictionary containing information about each connected client {IP: name, shared secret key}
    """
    def __init__(self):
        """
        A constructor for a Server class object.
        """
        self.name, self.ip, self.port = parse_arguments()
        self.own_socket = initialize_socket(self.ip, self.port)
        self.pvt_key, self.pub_key = generate_keys()
        self.sockets = [self.own_socket]
        self.client_dict = {}

    def start(self):
        """
        Starts the server and monitors any incoming connections
        and messages from existing clients.

        @return: None
        """
        while True:
            readable, _, _ = select.select(self.sockets, [], [])

            for sock in readable:
                # Accept a new connection and exchange keys
                if sock is self.own_socket:
                    accept_new_connection_handler(self, sock)
                else:
                    data = sock.recv(1024)
                    if data:
                        print("[+] Received data: ", data.decode())
                    else:
                        print("[+] Connection closed by client: ", sock.getpeername())
                        self.sockets.remove(sock)
                        sock.close()

